Добавлено имя наставника
htmlacademy-php/1215481-readme-12 pull request #1
Opened 2020-03-25 19:54 UTC by HA-student

2020-03-26 10:38 UTC, nkolosov requested changes

2020-03-26 10:38 UTC, nkolosov commented on Readme.md
> +* Наставник: `Никита Колосов`.
Сделай ссылку, как и со своим профилем

2020-03-26 19:15 UTC, HA-student commented on Readme.md
> +* Наставник: `Никита Колосов`.
Готово

2020-03-27 06:03 UTC, nkolosov approved these changes

2020-03-27 06:03 UTC, merged